config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
  root 'posts#index'

  get 'posts/:id/like' => 'posts#like', as: :like_post
  get 'my_posts' => 'posts#my_posts', as: :my_posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates :content, :presence => true
	has_many :post_likes
end

app/models/post_like.rb
class PostLike < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :user_id, :scope => [:post_id]
end

app/models/user.rb
class User < ActiveRecord::Base
include Clearance::User

	has_many :posts
	has_many :post_likes


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_rights, only: [:edit, :destroy]

  before_filter :authorize
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("rating DESC")
  end


  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def my_posts
    @posts = Post.where(user_id: current_user).reverse
    render "index"
  end


  def like
    @post = Post.find params[:id]
    @user = current_user

    if PostLike.where( :user_id => @user.id, :post_id => @post.id).empty?
      @like = PostLike.new
      @like.user = current_user
      @like.post = @post
      @like.save

      @post.rating = calculate_post_rating(@post)
      @post.save

      puts @post.inspect
    else
      puts "Allready liked "
    end

    redirect_to @post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content)
    end

    def calculate_post_rating post
      post_weight = Math::E ** (- (Time.now.to_i/86400 - post.created_at.to_i/86400))
      sum_of_like_weights = 0

      post.post_likes.each do |like|
        sum_of_like_weights += Math::E ** (- (Time.now.to_i/86400 - like.created_at.to_i/86400))
      end

      new_post_rating = post_weight * sum_of_like_weights
    end

    def check_rights
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false) if @post.user != current_user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_rights, only: [:edit, :destroy]
  
  before_filter :authorize, only: [:index, :show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :email, :picture, :back_image)
    end

    def check_rights
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false) if @user != current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eSwan</title>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tag %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
</head>
<body>
  <div id="background-swan"
  <% if signed_in? and !current_user.back_image.nil? -%>

    style="background-image: url(<%= current_user.back_image %>);"
  <% end %>
   ></div>
   <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">eSwan</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li <%= "class=active" if action_name == "index" %> ><a href="/posts">Posts</a></li>
            <% if signed_in? -%>
            <li <%= "class=active" if action_name == "my_posts"  %> ><a href="/my_posts">My Posts</a></li>
            <% end %>
          </ul>
          <ul class='nav navbar-nav navbar-right'>
            <% if signed_in? -%>
            <li><%= link_to "Hello, #{current_user.email}", current_user %></li>
              <li><%= link_to t('.sign_out'), sign_out_path, :method => :delete %></li>
            <% else -%>
              <li><%= link_to t('.sign_in'), sign_in_path %></li>
            <% end -%>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container page-container" style="max-width:900px;">
      <div class="row">
        <%= yield %>
      </div>
    </div> <!-- /container -->
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger">
      <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
      <ul>
      <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="post_entry">
    <%= f.text_area :content, :class => "new_post_field" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary"%>
  </div>
  <br/>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>


<%= link_to @post do %>
  <button class="btn btn-default">Show</button>
<% end %>

<%= link_to posts_path do %>
  <button class="btn btn-default">Back</button>
<% end %>

app/views/posts/index.html.erb
<%= link_to new_post_path do %>
  <button type="button" class="btn btn-default btn-lg">
    <span class="glyphicon glyphicon-pencil"></span> Write a new pretty post
  </button>
<% end %>
<br>
<br>

    <% @posts.each do |post| %>

      <div class="post">
        <div class="post-heading">
          <p>
          <%= post.user.email %>
          <span style="float:right; font-size:1.2em">
            <%= link_to like_post_path(post) do %>
              <span class="glyphicon glyphicon-heart"></span>
              <span class="likes-number"><%= post.post_likes.length %></span>
            <% end %>

            <% if post.user == current_user %>
              <%= link_to edit_post_path(post) do %>
                <span class="glyphicon glyphicon-edit"></span>
              <% end %>
              <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <span class="glyphicon glyphicon-trash"></span>
              <% end %>
          <% end %>
      </span>
        </p>
        </div>
        <%= link_to post do %>
        <div class="post-body">
          <p>
          <%= post.content %>
        </p>
        <span style="float: right">
          <%= post.created_at.strftime("%Y.%m.%d %H:%M") %>
        </span>
        </div>
        <% end %>
      </div>


    <% end %>

app/views/posts/new.html.erb
<div style="width:600px; margin:0 auto;">

	<h1>New post</h1>

	<%= render 'form' %>

</div>

app/views/posts/show.html.erb
<% if notice %>
	<div class="well">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>
<br><br>


 <div class="post">
  <div class="post-heading">
    <p>
    <%= @post.user.email %>
    <span style="float:right; font-size:1.2em">
      <%= link_to like_post_path(@post) do %>
        <span class="glyphicon glyphicon-heart"></span>
        <span class="likes-number"><%= @post.post_likes.length %></span>
      <% end %>

      <% if @post.user == current_user %>
        <%= link_to edit_post_path(@post) do %>
          <span class="glyphicon glyphicon-edit"></span>
        <% end %>
        <%= link_to @post, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      <% end %>
    </span>
    </p>
  </div>

  <div class="post-body">
    <p><%= @post.content %></p>
  <span style="float: right">
    <%= @post.created_at.strftime("%Y.%m.%d %H:%M") %>
  </span>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |form| %>

  <div class='text-field'>
    <%= form.label :username %>
    <br>
    <%= form.text_field :username %>
  </div>

  <div class='text-field'>
    <%= form.label :email %>
    <br>
    <%= form.text_field :email, :type => 'email' %>
  </div>

  <div class='password-field'>
    <%= form.label :password %>
    <br>
    <%= form.password_field :password %>
  </div>
  <br>

  <div class='text-field'>
    <%= form.label :picture %>
    <br>
    <%= form.text_field :picture %>
  </div>
  <br>
  <div class='text-field'>
    <%= form.label :back_image %>
    <br>
    <%= form.text_field :back_image %>
  </div>
  <br>

  <div class='submit-field'>
    <%= form.submit :class => "btn btn-primary" %>
  </div>
  <br>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All the unicorns</h1>


<% @users.each do |user| %>
  <div class="user">

    
      <div class="user_control">
      <% if user == current_user %>
        <%= link_to edit_user_path(user) do %>
          <span class="glyphicon glyphicon-edit"></span>
        <% end %>
        <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      <% end %>
    </div>

    <%= link_to user do %>
      <img class="user_picture"
      <% if user.picture.nil? %>
      src="http://i.imgur.com/4kW0zeD.png"
      <% else %>
        src="<%= user.picture %>"
      <% end %>
      >
    <% end %>

    <p class="name"><%= user.username %></p>
    <p class="email"><%= user.email %></p>
  </div>
<% end %>

app/views/users/new.html.erb
<div id='clearance' class='sign-up'>
  <h2><%= t('.title') %></h2>

  <%= form_for @user do |form| %>

    <div class='text-field'>
      <%= form.label :email %>
      <br>
      <%= form.text_field :email, :type => 'email' %>
    </div>

    <div class='password-field'>
      <%= form.label :password %>
      <br>
      <%= form.password_field :password %>
    </div>
    <br>

    <div class='submit-field'>
      <%= form.submit :class => "btn btn-primary" %>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<%= link_to users_path do %>
  <button type="button" class="btn btn-default btn-lg">
    <span class="glyphicon glyphicon-star"></span> Back to all users
  </button>
<% end %>

<br><br>

<% if notice %>
<div class="alert alert-success">
  <p id="notice"><%= notice %></p>
</div>
<% end %>

<div class="user">
  
  <div class="user_control">
    <% if @user == current_user %>
      <%= link_to edit_user_path(@user) do %>
       <span class="glyphicon glyphicon-edit"></span>
      <% end %>
      <%= link_to @user, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
<% end %>
  </div>

  <%= link_to @user do %>
    <img class="user_picture"
      <% if @user.picture.nil? %>
      src="http://i.imgur.com/4kW0zeD.png"
      <% else %>
        src="<%= @user.picture %>"
      <% end %>
      >
  <% end %>

  <p class="name"><%= @user.username %></p>
  <p class="email"><%= @user.email %></p>
</div>